/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISwapable, ISwapableInterface } from "../../contracts/ISwapable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_ERC20TokenAmount",
        type: "uint256",
      },
    ],
    name: "getAskPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_satiAmount",
        type: "uint256",
      },
    ],
    name: "getBidPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pairName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_ERC20TokenAmount",
        type: "uint256",
      },
    ],
    name: "swapBaseForQuoteToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_satiAmount",
        type: "uint256",
      },
    ],
    name: "swapQuoteForBaseToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ISwapable__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapableInterface {
    return new utils.Interface(_abi) as ISwapableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapable {
    return new Contract(address, _abi, signerOrProvider) as ISwapable;
  }
}
