/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { AstroStake } from "./AstroStake";
export type { AstroToken } from "./AstroToken";
export type { AstroTokenSale } from "./AstroTokenSale";
export type { ColorBox } from "./ColorBox";
export type { Crowdsale } from "./Crowdsale";
export type { ERC20TokensSwap } from "./ERC20TokensSwap";
export type { EthQuoteSwap } from "./EthQuoteSwap";
export type { Faucet } from "./Faucet";
export type { GovernanceOrchestrator } from "./GovernanceOrchestrator";
export type { GovernanceTimeLock } from "./GovernanceTimeLock";
export type { ISwapable } from "./ISwapable";
export type { KYCValidation } from "./KYCValidation";
export type { Ratable } from "./Ratable";
export type { SimpleStake } from "./SimpleStake";
export type { SwapContractFactory } from "./SwapContractFactory";
export type { Swapable } from "./Swapable";
