/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ISwapableInterface extends utils.Interface {
  functions: {
    "getAskPrice(uint256)": FunctionFragment;
    "getBidPrice(uint256)": FunctionFragment;
    "pairName()": FunctionFragment;
    "swapBaseForQuoteToken(uint256)": FunctionFragment;
    "swapQuoteForBaseToken(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getAskPrice"
      | "getBidPrice"
      | "pairName"
      | "swapBaseForQuoteToken"
      | "swapQuoteForBaseToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAskPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pairName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapBaseForQuoteToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapQuoteForBaseToken",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAskPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pairName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapBaseForQuoteToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapQuoteForBaseToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISwapable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISwapableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAskPrice(
      _ERC20TokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBidPrice(
      _satiAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pairName(overrides?: CallOverrides): Promise<[string]>;

    swapBaseForQuoteToken(
      _ERC20TokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapQuoteForBaseToken(
      _satiAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAskPrice(
    _ERC20TokenAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBidPrice(
    _satiAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pairName(overrides?: CallOverrides): Promise<string>;

  swapBaseForQuoteToken(
    _ERC20TokenAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapQuoteForBaseToken(
    _satiAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAskPrice(
      _ERC20TokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidPrice(
      _satiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pairName(overrides?: CallOverrides): Promise<string>;

    swapBaseForQuoteToken(
      _ERC20TokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapQuoteForBaseToken(
      _satiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAskPrice(
      _ERC20TokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBidPrice(
      _satiAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pairName(overrides?: CallOverrides): Promise<BigNumber>;

    swapBaseForQuoteToken(
      _ERC20TokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapQuoteForBaseToken(
      _satiAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAskPrice(
      _ERC20TokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBidPrice(
      _satiAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pairName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapBaseForQuoteToken(
      _ERC20TokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapQuoteForBaseToken(
      _satiAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
