/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface KYCValidationInterface extends utils.Interface {
  functions: {
    "KYCCompletedRegistry(address)": FunctionFragment;
    "requireKYCCompletion(address)": FunctionFragment;
    "seKYCCompletedFor(address)": FunctionFragment;
    "seKYCRevokedFor(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "KYCCompletedRegistry"
      | "requireKYCCompletion"
      | "seKYCCompletedFor"
      | "seKYCRevokedFor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "KYCCompletedRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "requireKYCCompletion",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "seKYCCompletedFor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "seKYCRevokedFor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "KYCCompletedRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireKYCCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seKYCCompletedFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seKYCRevokedFor",
    data: BytesLike
  ): Result;

  events: {};
}

export interface KYCValidation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KYCValidationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    KYCCompletedRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    requireKYCCompletion(
      _buyer: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    seKYCCompletedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    seKYCRevokedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  KYCCompletedRegistry(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  requireKYCCompletion(
    _buyer: string,
    overrides?: CallOverrides
  ): Promise<void>;

  seKYCCompletedFor(
    _userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  seKYCRevokedFor(
    _userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    KYCCompletedRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    requireKYCCompletion(
      _buyer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    seKYCCompletedFor(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    seKYCRevokedFor(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    KYCCompletedRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requireKYCCompletion(
      _buyer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seKYCCompletedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    seKYCRevokedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    KYCCompletedRegistry(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requireKYCCompletion(
      _buyer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seKYCCompletedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    seKYCRevokedFor(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
