/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface RatableInterface extends utils.Interface {
  functions: {
    "getScaledRate(uint8)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getScaledRate"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getScaledRate",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getScaledRate",
    data: BytesLike
  ): Result;

  events: {
    "Rate(int256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Rate"): EventFragment;
}

export interface RateEventObject {
  scaledPrice: BigNumber;
  timeStamp: BigNumber;
}
export type RateEvent = TypedEvent<[BigNumber, BigNumber], RateEventObject>;

export type RateEventFilter = TypedEventFilter<RateEvent>;

export interface Ratable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RatableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getScaledRate(
      _scalingDecimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getScaledRate(
    _scalingDecimal: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getScaledRate(
      _scalingDecimal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Rate(int256,uint256)"(
      scaledPrice?: BigNumberish | null,
      timeStamp?: BigNumberish | null
    ): RateEventFilter;
    Rate(
      scaledPrice?: BigNumberish | null,
      timeStamp?: BigNumberish | null
    ): RateEventFilter;
  };

  estimateGas: {
    getScaledRate(
      _scalingDecimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getScaledRate(
      _scalingDecimal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
